apiVersion: v1
kind: Pod
metadata:
  name: aws-dla-demo
spec:
  containers:
  - name: aws-dla-demo
    image: containerhub.xelera.io:4433/aws-dla-demo:1.0
    securityContext:
      privileged: true
    resources:
      limits:
        xilinx.com/fpga-xilinx_aws-vu9p-f1-04261818_dynamic_5_0-0: 1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    volumeMounts:
      - name: sys
        mountPath: /sys
  volumes:
    - name: sys
      hostPath:
        path: /sys
  imagePullSecrets:
    - name: regcred
